/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "corenlp_constants.h"



const corenlpConstants g_corenlp_constants;

corenlpConstants::corenlpConstants() {
}



