/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef corenlp_CONSTANTS_H
#define corenlp_CONSTANTS_H

#include "corenlp_types.h"



class corenlpConstants {
 public:
  corenlpConstants();

};

extern const corenlpConstants g_corenlp_constants;



#endif
